import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { useGLTF, Text, Html, Float } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import gsap from "gsap";
import ToggleFocusButton from "../utils/ToggleFocusButton.jsx";
import { person } from "@/data/resume";
import { VICE } from "../theme";

/**
 * Home scene: a floating laptop whose screen boots MAHARSHI.OS, plus the
 * name plate and a focus button. Adapted from Eli Parker's MIT-licensed
 * interactive portfolio and reskinned for the Vice City theme.
 *
 * @param {Function} onLoad - called the first time the scene mounts.
 */
const LaptopScene = forwardRef(({ onLoad = () => {} }, ref) => {
  const font = "/fonts/anek-bangla-v5-latin-500.woff";

  const [isAnimating, setIsAnimating] = useState(false);

  // Tell Experience we exist so it can animate us in
  useEffect(() => {
    onLoad();
  }, []);

  const scene = useRef();
  const { camera } = useThree();

  useImperativeHandle(ref, () => ({
    scale: scene.current.scale,

    // Springy scale toggle between hidden (0) and shown (1)
    toggleAnimateOut: () => {
      if (!isAnimating) {
        setIsAnimating(true);
        scene.current.visible = true;

        const targetScale =
          scene.current.scale.x === 1 ? { x: 0, y: 0, z: 0 } : { x: 1, y: 1, z: 1 };

        gsap.to(scene.current.scale, {
          duration: 0.5,
          x: targetScale.x,
          y: targetScale.y,
          z: targetScale.z,
          ease: "power2.inOut",
          onUpdate: () => camera.updateProjectionMatrix(),
          onComplete: () => {
            if (targetScale.x === 0) scene.current.visible = false;
            setIsAnimating(false);
          },
        });
      }
    },

    // Instant toggle used when switching pages
    toggleOut: () => {
      if (!isAnimating) {
        setIsAnimating(true);
        scene.current.visible = true;
        if (scene.current.scale.x > 0) {
          scene.current.scale.set(0, 0, 0);
          scene.current.visible = false;
        } else {
          scene.current.scale.set(1, 1, 1);
        }
        setIsAnimating(false);
      }
    },
  }));

  return (
    <group ref={scene} scale={0} visible={false}>
      <Float rotationIntensity={0.4}>
        {/* Laptop + screen */}
        <group position-y={-1.2}>
          <LaptopModel />

          {/* MAHARSHI.OS boot screen rendered onto the laptop display */}
          <Html
            transform
            wrapperClass="htmlScreen"
            distanceFactor={1.14}
            position={[0, 1.52, -1.35]}
            rotation-x={-0.256}
          >
            <div className="viceScreen">
              <div className="viceScreen__bar">
                <span className="viceScreen__dot" style={{ background: VICE.pink }} />
                <span className="viceScreen__dot" style={{ background: VICE.gold }} />
                <span className="viceScreen__dot" style={{ background: VICE.cyan }} />
                <span className="viceScreen__title">MAHARSHI.OS — vice://boot</span>
              </div>
              <div className="viceScreen__body">
                <p className="viceScreen__line">&gt; booting neon runtime…</p>
                <p className="viceScreen__line">&gt; loading identity.pkg</p>
                <h1 className="viceScreen__name">{person.name}</h1>
                <p className="viceScreen__role">{person.role}</p>
                <p className="viceScreen__tag">&quot;{person.tagline}&quot;</p>
                <p className="viceScreen__hint">
                  drag to look around · use the nav to explore
                  <span className="viceScreen__caret">▋</span>
                </p>
              </div>
            </div>
          </Html>
        </group>

        {/* Name plate */}
        <Text
          font={font}
          fontSize={0.7}
          position={[2.5, 0.5, -0.3]}
          rotation-y={-1}
          rotation-z={0.1}
          maxWidth={2}
          lineHeight={1}
          color={VICE.pink}
        >
          {person.name}
        </Text>

        {/* Hint */}
        <Text
          font={font}
          fontSize={0.125}
          position={[-2, 0.75, -1.25]}
          rotation={[-0, -0.1, 0]}
          maxWidth={2}
          lineHeight={1}
          color={VICE.cyan}
        >
          {"Drag me! ↔"}
        </Text>

        {/* Move closer / away */}
        <ToggleFocusButton position={[0, 1.6, -1.8]} />
      </Float>
    </group>
  );
});

export default LaptopScene;

/**
 * The MacBook GLTF, auto-generated by gltfjsx.
 * Model: "Computer Monitor Lowpoly" family — MacBook model, CC-BY.
 */
export function LaptopModel(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/laptop/macbook_model.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.52, 0]} scale={[0.1, 0.1, 0.1]}>
        <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} />
        <mesh geometry={nodes.Circle001_1.geometry} material={nodes.Circle001_1.material} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.HeadPhoneHole} />
        <mesh geometry={nodes.Circle001_3.geometry} material={nodes.Circle001_3.material} />
        <mesh geometry={nodes.Circle001_4.geometry} material={nodes.Circle001_4.material} />
        <mesh geometry={nodes.Circle001_5.geometry} material={materials.TouchbarBorder} />
        <mesh geometry={nodes.Circle001_6.geometry} material={materials.Keyboard} />
        <mesh
          geometry={nodes.FrontCameraRing001.geometry}
          material={materials["CameraRIngBlack.002"]}
          position={[-0.15, 19.57, -16.15]}
          scale={5.8}
        />
        <mesh
          geometry={nodes.KeyboardKeyHole.geometry}
          material={nodes.KeyboardKeyHole.material}
          position={[-11.79, -0.15, -8.3]}
          scale={5.8}
        />
        <mesh
          geometry={nodes.RubberFoot.geometry}
          material={materials.DarkRubber}
          position={[-11.95, -0.75, 7.86]}
          scale={5.8}
        />

        {/* Hinge */}
        <group position={[0.01, -0.21, -10.56]} scale={5.8}>
          <mesh geometry={nodes.Circle012.geometry} material={materials.HingeBlack} />
          <mesh geometry={nodes.Circle012_1.geometry} material={materials.HingeMetal} />
        </group>

        {/* Bottom case */}
        <group position={[0, -0.51, 0]} scale={5.8}>
          <mesh geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} />
          <mesh geometry={nodes.Circle006_1.geometry} material={nodes.Circle006_1.material} />
        </group>

        {/* Keyboard */}
        <group position={[-11.79, -0.15, -8.3]} scale={5.8}>
          <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} />
          <mesh geometry={nodes.Circle_1.geometry} material={materials.Key} />
          <mesh geometry={nodes.Circle_2.geometry} material={materials.Touchbar} />
        </group>

        {/* Screen */}
        <group position={[0.01, -0.47, -10.41]} rotation={[1.31, 0, 0]} scale={5.8}>
          <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Circle002_2.geometry} material={materials.ScreenGlass} />
        </group>

        <group position={[12.2, 0.03, 0.6]} scale={5.8}>
          <mesh geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} />
          <mesh geometry={nodes.Circle003_1.geometry} material={nodes.Circle003_1.material} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/laptop/macbook_model.gltf");
